[server]
address="dksrv206:35700"
port=7701
cache=false

[[server.route]]
path="/portfolio"
ifs="$POPATH"

[[server.route]]
path="/icecap"
ifs="$POPATH/../icecap"

[[server.route]]
path="/ip2Base"
ifs="$POPATH"

[[server.route]]
path="/wsh-widgets"
ifs="$POPATH/../wsh/widgets"

[[server.route]]
path="/tooling"
ifs="$POPATH/../projects/tooling/apps/"

[[server.route]]
path="/system/shared/ext-6.6.0/build"
ifs="%localappdata%\\devx\\ext-6.6.0\\build\\"

[[server.route]]
path="/system/shared/theme/sitemule-theme-desktop"
ifs="$POPATH/../themes/sitemule/packages/local/sitemule-theme-desktop/build/"

[[server.route]]
path="/system/shared/theme/sitemule-theme-desktop-olive"
ifs="$POPATH/../themes/sitemule/packages/local/sitemule-theme-desktop-olive/build/"

[[server.route]]
path="/system/shared/theme/sitemule-theme-desktop-cherry"
ifs="$POPATH/../themes/sitemule/packages/local/sitemule-theme-desktop-cherry/build/"

[[server.route]]
path="/system/shared/theme/sitemule-theme-desktop-ocean"
ifs="$POPATH/../themes/sitemule/packages/local/sitemule-theme-desktop-ocean/build/"

[[server.route]]
path="/system/shared/theme/sitemule-theme-desktop-slate"
ifs="$POPATH/../themes/sitemule/packages/local/sitemule-theme-desktop-slate/build/"

[[server.route]]
path="/system/shared/theme/sitemule-theme-desktop-dark"
ifs="$POPATH/../themes/sitemule/packages/local/sitemule-theme-desktop-dark/build/"

[[server.route]]
path="/system/shared/theme/sitemule-theme-desktop-dark-blue"
ifs="$POPATH/../themes/sitemule/packages/local/sitemule-theme-desktop-dark-blue/build/"

[[server.route]]
path="/system/shared/theme/sitemule-theme-desktop-dark-ibmi"
ifs="$POPATH/../themes/sitemule/packages/local/sitemule-theme-desktop-dark-ibmi/build/"

[[server.route]]
path="/icecaputils"
ifs="$POPATH/../icecap-utils"

[[server.route]]
path="/portfolio/mnu/{*path}"

[[server.route]]
path="/portfolio/cms/{*path}"

[[server.route]]
path="/portfolio/usr/{*path}"

[[server.route]]
path="/portfolio/ntf/{*path}"

[[server.route]]
path="/portfolio/bld/{*path}"

[[server.route]]
path="/portfolio/mnuntfsck/{*path}"

[[server.route]]
path="/cms-media/{*path}"

[[server.route]]
path="/setPassword/{*path}"

[[server.route]]
path="/system/{*path}"